
# Ce Makefile sert à faciliter la mise à jour de la documentation,
# quand celle-ci a effectivement été modifiée. Pour l'utiliser : make.



# Documentation folder
DOC=./Documentation

# Library folder
LIB=./Tortuino

# Doxygen configuration file
DGN=./DoxyConfig

# Make output log file
LOG=./make.log

# Make timestamp file
MTS=./make.timestamp

# LaTeX header file
LHD=$(DOC)/latex/header.tex


$(MTS): $(LIB)/Tortuino.h $(LIB)/Tortuino.cpp $(LIB)/TortuinoDessins.h $(LIB)/TortuinoDessins.cpp
	@echo "[make] Started documentation make log." | tee $(LOG)
	
	@echo "[make] Generating custom LaTeX header...\n" | tee -a $(LOG)
	@rm -f $(LHD)*
	doxygen -w latex $(LHD) /dev/null /dev/null $(DGN)
	sed -i 's={\\Large Your title here}\\\\=\\includegraphics\[width\=100mm\,scale\=0.5\]{../../Images/logo-tortuino.png}\\\\\n\\vspace*{3cm}\n{\\Large Documentation $$projectname}\\\\=g' $(LHD)
	@rm -f $(LHD).*
	sed -i 's/Generated by/Généré par/g' $(LHD)
	@rm -f $(LHD).*
	@echo "\n[make] Custom LaTeX header generation finished." | tee -a $(LOG)
	
	@echo "[make] Calling Doxygen for the rest...\n" | tee -a $(LOG)
	outDir=$(DOC) doxygen $(DGN) >> $(LOG)
	@echo "\n[make] Doxygen finished." | tee -a $(LOG)
	
	@echo "[make] Calling the PDF make...\n" | tee -a $(LOG)
	make -C $(DOC)/latex/ >> $(LOG)
	@rm -f $(LHD)*
	@echo "\n[make] PDF make finished." | tee -a $(LOG)
	
	@echo "[make] Updating make.timestamp...\n" | tee -a $(LOG)
	touch $(MTS)
	@echo "\n[make] make.timestamp update finished." | tee -a $(LOG)
	
	@echo "[make] Documentation make log ended." | tee -a $(LOG)

cleanall:
	@echo "[make] Removing auto-generated files from . and from $(DOC)..."
	rm -rf $(DOC)/*
	rm -f $(LOG)
	@echo "[make] Removal finished."
